import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Admin.module.css'

import { signOut, signIn, getSession } from 'next-auth/client'

import { User } from '@prisma/client'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession({ req: context.req })

  return {
    props: {
      user: session?.user || null,
    },
  }
}

interface PageProps {
  user: Partial<User>
}

export default function Home(props: PageProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Strong-js Admnin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Strong-js Admin App</h1>
        <br />

        {props?.user?.email ? (
          <div>
            Signed in as{' '}
            <code className={styles.code}>{props?.user?.email}</code>
            <a href="#" onClick={() => signOut()}>
              Sign out
            </a>
          </div>
        ) : (
          <a href="#" onClick={() => signIn()}>
            Sign in
          </a>
        )}
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/admin/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
