backend:
  - backend/*
  - backend/**/*

data:
  - packages/data/*
  - packages/data/**/*

generate:
  - packages/generate/*
  - packages/generate/**/*

cypress:
  - cypress/*
  - cypress/**/*

repo:
  - ./*
