version: '3'

services:
  db:
    image: postgres:13.1
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=test
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'root']
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - 5432:5432
