name: End to End Web
on:
  push
  # pull_request:
  #   branches:
  #     - main

jobs:
  cypress:
    name: Build and run End to End Web tests on ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: cypress/browsers:node12.18.3-chrome87-ff82
    services:
      postgres:
        image: postgres:13.3
        volumes:
          - ./db:/docker-entrypoint-initdb.d/
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          APP_DB_USER: postgres
          APP_DB_PASS: postgres
          APP_DB_NAME: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        env:
          PRISMA_SKIP_POSTINSTALL_GENERATE: true

      - name: Create Database
        shell: bash
        run: |
          < ${{ env.ENV_FILE }} >> $GITHUB_ENV
          npx prisma db push --accept-data-loss
        env:
          ENV_FILE: 'apps/web/app-main/.env.test'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn apps:web:build
          start: yarn apps:web:start
        shell: bash
        run: |
          < ${{ env.ENV_FILE }} >> $GITHUB_ENV
        env:
          ENV_FILE: 'apps/web/app-main/.env.test'

      - name: Upload Screenshots if tests fail
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
